package com.saraya.schoolmanagement.enums;

public enum RoleName {
    ROLE_ADMIN,ROLE_USER,ROLE_EMPLOYEE,ROLE_STUDENT,ROLE_PARENT,ROLE_BOOKKEEPER,
    ROLE_TEACHER,ROLE_SECRETARY,ROLE_DEPARTMENTMANAGER
}
